// Botun gönderdiği TÜM metinlerin varsayılanları. Web panelinden düzenlenebilir.
// Satır: [anahtar, etiket, varsayılan, değişkenler[], tür]
// Türler (Discord sınırı): text 2000 | title 256 | button 80 | short 100 | label45 45 | color #RRGGBB
const entries = [];
const section = (group, rows) => {
  for (const [key, label, value, vars = [], kind = 'text'] of rows) entries.push({ group, key, label, value, vars, kind });
};

section('Renkler', [
  ['color.main', 'Ana renk', '#5865F2', [], 'color'],
  ['color.success', 'Başarı rengi', '#57F287', [], 'color'],
  ['color.warn', 'Uyarı rengi', '#FEE75C', [], 'color'],
  ['color.danger', 'Hata/ceza rengi', '#ED4245', [], 'color'],
  ['color.info', 'Bilgi rengi', '#3498DB', [], 'color'],
  ['color.ticket', 'Destek paneli / bilet rengi', '#1DB924', [], 'color'],
]);

section('Genel', [
  ['mod.noreason', 'Sebep girilmediğinde', 'Sebep belirtilmedi', [], 'short'],
  ['generic.error', 'Beklenmeyen hata', 'Bir hata oluştu, lütfen daha sonra tekrar dene.'],
  ['generic.ok_prefix', 'Başarı mesajı ön eki (emoji)', '✅', [], 'label45'],
  ['generic.fail_prefix', 'Hata mesajı ön eki (emoji)', '❌', [], 'label45'],
  ['generic.nopermission', 'Yetki yok', 'Bunun için yetkin yok.'],
  ['generic.failed', 'İşlem başarısız', 'Yapılamadı: {error}', ['error']],
  ['generic.notinguild', 'Kullanıcı sunucuda değil', 'Kullanıcı sunucuda değil.'],
  ['generic.bots_na', 'Botlar için kullanılamaz', 'Botlar için kullanılamaz.'],
  ['unit.day', 'Süre birimi: gün', 'gün', [], 'label45'],
  ['unit.hour', 'Süre birimi: saat', 'saat', [], 'label45'],
  ['unit.minute', 'Süre birimi: dakika', 'dk', [], 'label45'],
  ['unit.second', 'Süre birimi: saniye', 'sn', [], 'label45'],
]);

section('Moderasyon — Kontroller', [
  ['mod.target.self', 'Kendine işlem', 'Kendine bu işlemi uygulayamazsın.'],
  ['mod.target.bot', 'Bota işlem', 'Bana bu işlemi uygulayamazsın.'],
  ['mod.target.owner', 'Sunucu sahibine işlem', 'Sunucu sahibine işlem uygulanamaz.'],
  ['mod.target.hierarchy', 'Rol hiyerarşisi (yetkili)', 'Bu kullanıcının rolü seninkiyle aynı ya da senden yüksek.'],
  ['mod.target.botcant', 'Rol hiyerarşisi (bot)', 'Bu kullanıcıya işlem uygulayamıyorum (rolü benden yüksek olabilir).'],
]);

section('Moderasyon — Ceza kaydı (log & DM)', [
  ['case.title', 'Log embed başlığı', '{emoji} {type} | Ceza #{case}', ['emoji', 'type', 'case'], 'title'],
  ['case.field.user', 'Alan: Kullanıcı', 'Kullanıcı', [], 'title'],
  ['case.field.mod', 'Alan: Yetkili', 'Yetkili', [], 'title'],
  ['case.field.reason', 'Alan: Sebep', 'Sebep', [], 'title'],
  ['case.field.duration', 'Alan: Süre', 'Süre', [], 'title'],
  ['case.auto', 'Otomatik yetkili adı', '🤖 Otomatik', [], 'short'],
  ['case.type.ban', 'Tür: Yasaklama', 'Yasaklama', [], 'short'],
  ['case.type.unban', 'Tür: Yasak kaldırma', 'Yasak Kaldırma', [], 'short'],
  ['case.type.kick', 'Tür: Atma', 'Atma', [], 'short'],
  ['case.type.sustur', 'Tür: Susturma', 'Susturma', [], 'short'],
  ['case.type.susturma_kaldir', 'Tür: Susturma kaldırma', 'Susturma Kaldırma', [], 'short'],
  ['case.type.uyari', 'Tür: Uyarı', 'Uyarı', [], 'short'],
  ['case.type.otomod', 'Tür: Otomatik moderasyon', 'Otomatik Moderasyon', [], 'short'],
  ['case.escalation_reason', 'Otomatik susturma sebebi', '{count} aktif uyarıya ulaşıldı (otomatik)', ['count'], 'short'],
  ['dm.title', 'Cezalıya DM başlığı', '{guild} | Ceza #{case}', ['guild', 'case'], 'title'],
  ['dm.footer', 'Cezalıya DM alt yazısı', 'Haksız olduğunu düşünüyorsan itiraz edebilirsin', [], 'short'],
  ['dm.hint', 'Cezalıya DM itiraz bilgisi', 'İtiraz için `/itiraz ceza-no:{case}` komutunu kullan (sunucuda ya da bana DM\'den).', ['case']],
]);

section('Moderasyon — Komut yanıtları', [
  ['mod.ban.self', '/ban: kendini', 'Kendini yasaklayamazsın.'],
  ['mod.ban.failed', '/ban: hata', 'Yasaklanamadı: {error}', ['error']],
  ['mod.ban.success', '/ban: başarılı', '**{user}** yasaklandı. (Ceza #{case})', ['user', 'case']],
  ['mod.unban.notfound', '/unban: bulunamadı', 'Bu ID ile yasaklı bir kullanıcı bulunamadı.'],
  ['mod.unban.success', '/unban: başarılı', '`{id}` kullanıcısının yasağı kaldırıldı.', ['id']],
  ['mod.kick.failed', '/at: hata', 'Atılamadı: {error}', ['error']],
  ['mod.kick.success', '/at: başarılı', '**{user}** sunucudan atıldı. (Ceza #{case})', ['user', 'case']],
  ['mod.timeout.badduration', '/sustur: geçersiz süre', 'Geçersiz süre. Örnek: `30m`, `2h`, `1d` (en fazla 28 gün).'],
  ['mod.timeout.failed', '/sustur: hata', 'Susturulamadı: {error}', ['error']],
  ['mod.timeout.success', '/sustur: başarılı', '**{user}** {duration} susturuldu. (Ceza #{case})', ['user', 'duration', 'case']],
  ['mod.untimeout.notmuted', '/susturma-kaldir: susturulmamış', 'Bu kullanıcı susturulmuş değil.'],
  ['mod.untimeout.failed', '/susturma-kaldir: hata', 'Kaldırılamadı: {error}', ['error']],
  ['mod.untimeout.success', '/susturma-kaldir: başarılı', '**{user}** kullanıcısının susturması kaldırıldı.', ['user']],
  ['mod.warn.bot', '/uyar: bot', 'Botlara uyarı verilemez.'],
  ['mod.warn.success', '/uyar: başarılı', '**{user}** uyarıldı. (Ceza #{case}, aktif uyarı: {count})', ['user', 'case', 'count']],
  ['mod.warn.escalated', '/uyar: eşik aşıldı eki', '⏱️ Eşik aşıldığı için otomatik susturuldu (Ceza #{case}).', ['case']],
  ['mod.warns.empty', '/uyarilar: boş', 'Bu kullanıcının uyarısı yok.'],
  ['mod.warns.title', '/uyarilar: başlık', '{user} — Uyarılar', ['user'], 'title'],
  ['mod.warns.line', '/uyarilar: satır', '{icon} **#{case}** {date} — {reason} ({mod})', ['icon', 'case', 'date', 'reason', 'mod']],
  ['mod.warns.footer', '/uyarilar: alt yazı', 'Aktif: {active} / Toplam: {total}  •  🟡 aktif  ⚪ geçersiz', ['active', 'total'], 'short'],
  ['mod.delwarn.notfound', '/uyari-sil: bulunamadı', 'Bu numarada bir uyarı bulunamadı.'],
  ['mod.delwarn.log', '/uyari-sil: log mesajı', '🧹 **Uyarı #{case}** (<@{target}>) <@{mod}> tarafından geçersiz kılındı.', ['case', 'target', 'mod']],
  ['mod.delwarn.success', '/uyari-sil: başarılı', 'Uyarı #{case} geçersiz kılındı.', ['case']],
  ['mod.cases.clean', '/cezalar: sicil temiz', 'Bu kullanıcının sicili temiz. ✨'],
  ['mod.cases.title', '/cezalar: başlık', '{user} — Ceza Geçmişi', ['user'], 'title'],
  ['mod.cases.line', '/cezalar: satır', '{emoji} **#{case}** {type} {date} — {reason}', ['emoji', 'case', 'type', 'date', 'reason']],
  ['mod.cases.footer', '/cezalar: alt yazı', 'Toplam {total} kayıt', ['total'], 'short'],
  ['mod.purge.unavailable', '/temizle: kullanılamaz', 'Bu kanalda kullanılamaz.'],
  ['mod.purge.log', '/temizle: log mesajı', '🧹 <@{mod}> {channel} kanalında **{count}** mesaj sildi{target}.', ['mod', 'channel', 'count', 'target']],
  ['mod.purge.success', '/temizle: başarılı', '{count} mesaj silindi. (14 günden eski mesajlar silinemez)', ['count']],
  ['mod.purge.failed', '/temizle: hata', 'Silinemedi: {error}', ['error']],
  ['mod.lock.log', '/kilitle: log mesajı', '🔒 <@{mod}> {channel} kanalını kilitledi.', ['mod', 'channel']],
  ['mod.unlock.log', '/kilit-ac: log mesajı', '🔓 <@{mod}> {channel} kanalını açtı.', ['mod', 'channel']],
  ['mod.lock.success', '/kilitle: başarılı', '{channel} kilitlendi.', ['channel']],
  ['mod.unlock.success', '/kilit-ac: başarılı', '{channel} kilidi açıldı.', ['channel']],
  ['mod.slow.on', '/yavasmod: açıldı', '{channel} yavaş modu **{seconds} sn** yapıldı.', ['channel', 'seconds']],
  ['mod.slow.off', '/yavasmod: kapatıldı', '{channel} yavaş modu kapatıldı.', ['channel']],
]);

section('Seviye sistemi', [
  ['level.up', 'Seviye atlama duyurusu', '🎉 Tebrikler {user}, **{level}. seviye** oldun!', ['user', 'level']],
  ['level.bot', '/seviye: bot', 'Botların seviyesi yok.'],
  ['level.noxp', '/seviye: XP yok', '**{user}** henüz hiç XP kazanmamış.', ['user']],
  ['level.field.level', '/seviye alan: Seviye', 'Seviye', [], 'title'],
  ['level.field.rank', '/seviye alan: Sıralama', 'Sıralama', [], 'title'],
  ['level.field.messages', '/seviye alan: Mesaj', 'Mesaj', [], 'title'],
  ['level.field.next', '/seviye alan: Sonraki seviye', 'Sonraki seviye ({current}/{needed} XP)', ['current', 'needed'], 'title'],
  ['level.footer', '/seviye alt yazı', 'Toplam XP: {xp}', ['xp'], 'short'],
  ['level.board.title', '/siralama başlık', '🏆 {guild} Sıralaması', ['guild'], 'title'],
  ['level.board.empty', '/siralama boş', 'Henüz sıralamada kimse yok.'],
  ['level.board.line', '/siralama satır', '{pos} <@{id}> — Seviye **{level}** • {xp} XP', ['pos', 'id', 'level', 'xp']],
  ['level.board.footer', '/siralama alt yazı', 'Sayfa {page}/{pages}', ['page', 'pages'], 'short'],
  ['level.cfg.role_invalid', 'rol-ekle: geçersiz rol', 'Bu rol verilemez (bot/entegrasyon rolü ya da @everyone).'],
  ['level.cfg.role_high', 'rol-ekle: rol çok yüksek', 'Bu rol benim rolümden yüksek; rolümü yukarı taşı.'],
  ['level.cfg.role_set', 'rol-ekle: başarılı', '**Seviye {level}** → {role} olarak ayarlandı.', ['level', 'role']],
  ['level.cfg.role_removed', 'rol-sil: başarılı', 'Seviye {level} rolü kaldırıldı.', ['level']],
  ['level.cfg.role_none', 'rol-sil: rol yok', 'Bu seviyede rol yok.'],
  ['level.cfg.roles_title', 'roller: başlık', 'Seviye Rolleri', [], 'title'],
  ['level.cfg.roles_empty', 'roller: boş', 'Henüz seviye rolü yok.'],
  ['level.cfg.roles_line', 'roller: satır', '**Seviye {level}** → <@&{role}>', ['level', 'role']],
  ['level.cfg.on', 'durum: açıldı', 'Seviye sistemi açıldı.'],
  ['level.cfg.off', 'durum: kapatıldı', 'Seviye sistemi kapatıldı.'],
  ['level.cfg.xp', 'xp-ver: başarılı', '{user} artık **{xp} XP** ve **{level}. seviye**.', ['user', 'xp', 'level']],
  ['level.cfg.reset', 'sifirla: başarılı', '{user} kullanıcısının seviyesi sıfırlandı.', ['user']],
]);

section('Rapor sistemi', [
  ['report.title', 'Rapor embed başlığı', '📢 Rapor #{id}', ['id'], 'title'],
  ['report.field.reporter', 'Alan: Raporlayan', 'Raporlayan', [], 'title'],
  ['report.field.target', 'Alan: Raporlanan', 'Raporlanan', [], 'title'],
  ['report.field.status', 'Alan: Durum', 'Durum', [], 'title'],
  ['report.field.reason', 'Alan: Sebep', 'Sebep', [], 'title'],
  ['report.field.evidence', 'Alan: Kanıt', 'Kanıt', [], 'title'],
  ['report.status.pending', 'Durum: bekliyor', 'bekliyor', [], 'short'],
  ['report.status.resolved', 'Durum: çözüldü', 'çözüldü', [], 'short'],
  ['report.status.rejected', 'Durum: reddedildi', 'reddedildi', [], 'short'],
  ['report.status.handled', 'Durum satırı (sonuçlanmış)', '{status} (<@{mod}>)', ['status', 'mod'], 'short'],
  ['report.btn.accept', 'Buton: işlem yapıldı', '✅ İşlem yapıldı', [], 'button'],
  ['report.btn.reject', 'Buton: geçersiz', '🚫 Geçersiz', [], 'button'],
  ['report.no_channel', 'Rapor kanalı yok', 'Rapor kanalı ayarlanmamış. Bir yöneticiye `/ayar rapor-kanali` kullanmasını söyle.'],
  ['report.self', 'Kendini raporlama', 'Kendini raporlayamazsın.'],
  ['report.limit', 'Bekleyen rapor limiti', 'En fazla {max} bekleyen raporun olabilir. Lütfen yetkililerin ilgilenmesini bekle.', ['max']],
  ['report.sent', 'Rapor gönderildi', 'Raporun yetkililere iletildi. (Rapor #{id})', ['id']],
  ['report.already', 'Rapor zaten sonuçlanmış', 'Bu rapor zaten sonuçlandırılmış.'],
  ['report.dm.resolved', 'Raporlayana DM: işlem yapıldı', '✅ **{guild}** sunucusundaki **#{id}** numaralı raporun incelendi ve gerekli işlem yapıldı. Teşekkürler!', ['guild', 'id']],
  ['report.dm.rejected', 'Raporlayana DM: geçersiz', 'ℹ️ **{guild}** sunucusundaki **#{id}** numaralı raporun incelendi ancak işlem gerektirmediği değerlendirildi.', ['guild', 'id']],
  ['report.cmd.bot', '/rapor: bot', 'Botlar raporlanamaz.'],
  ['report.modal.title', 'Mesaj raporu penceresi başlığı', 'Mesajı Raporla', [], 'label45'],
  ['report.modal.label', 'Pencere alan etiketi', 'Sebep', [], 'label45'],
  ['report.modal.placeholder', 'Pencere ipucu metni', 'Bu mesajda ne sorun var?', [], 'short'],
]);

section('İtiraz sistemi', [
  ['appeal.title', 'İtiraz embed başlığı', '⚖️ İtiraz #{id} — Ceza #{case} ({type})', ['id', 'case', 'type'], 'title'],
  ['appeal.field.user', 'Alan: İtiraz eden', 'İtiraz eden', [], 'title'],
  ['appeal.field.giver', 'Alan: Cezayı veren', 'Cezayı veren', [], 'title'],
  ['appeal.field.status', 'Alan: Durum', 'Durum', [], 'title'],
  ['appeal.field.case_reason', 'Alan: Ceza sebebi', 'Ceza sebebi', [], 'title'],
  ['appeal.field.text', 'Alan: İtiraz metni', 'İtiraz metni', [], 'title'],
  ['appeal.status.pending', 'Durum: bekliyor', 'bekliyor', [], 'short'],
  ['appeal.status.accepted', 'Durum: kabul edildi', 'kabul edildi', [], 'short'],
  ['appeal.status.rejected', 'Durum: reddedildi', 'reddedildi', [], 'short'],
  ['appeal.status.handled', 'Durum satırı (sonuçlanmış)', '{status} (<@{mod}>)', ['status', 'mod'], 'short'],
  ['appeal.btn.accept', 'Buton: kabul et', '✅ Kabul et', [], 'button'],
  ['appeal.btn.reject', 'Buton: reddet', '🚫 Reddet', [], 'button'],
  ['appeal.notfound', 'Ceza bulunamadı', 'Bu numarada sana ait bir ceza bulunamadı.'],
  ['appeal.notappealable', 'İtiraz edilemez tür', 'Bu kayıt türüne itiraz edilemez.'],
  ['appeal.inactive', 'Ceza zaten kaldırılmış', 'Bu ceza zaten geçersiz ya da kaldırılmış.'],
  ['appeal.pending', 'Bekleyen itiraz var', 'Bu ceza için zaten bekleyen bir itirazın var.'],
  ['appeal.no_channel', 'İtiraz kanalı yok', 'Bu sunucuda itiraz kanalı ayarlanmamış; bir yetkiliyle iletişime geç.'],
  ['appeal.sent', 'İtiraz gönderildi', 'İtirazın yetkililere iletildi. (İtiraz #{id}) Sonucu sana DM ile bildirilecek; DM\'lerini açık tut.', ['id']],
  ['appeal.already', 'İtiraz zaten sonuçlanmış', 'Bu itiraz zaten sonuçlandırılmış.'],
  ['appeal.noperm', 'Yetki yok', 'Bu itirazı sonuçlandırmak için yetkin yok.'],
  ['appeal.own', 'Kendi cezasına itiraz', 'Kendi verdiğin cezaya yapılan itirazı sonuçlandıramazsın; başka bir yetkili baksın.'],
  ['appeal.revert_reason', 'Ceza geri alma sebebi (denetim kaydı)', 'İtiraz #{id} kabul edildi ({mod})', ['id', 'mod'], 'short'],
  ['appeal.log', 'Mod-log mesajı', '⚖️ **İtiraz #{id}** (Ceza #{case}, <@{user}>) <@{mod}> tarafından **{result}**.', ['id', 'case', 'user', 'mod', 'result']],
  ['appeal.dm.accepted', 'Kullanıcıya DM: kabul', '✅ **{guild}** sunucusundaki **#{case}** numaralı ceza için itirazın **kabul edildi**; ceza kaldırıldı.', ['guild', 'case']],
  ['appeal.dm.rejected', 'Kullanıcıya DM: red', '🚫 **{guild}** sunucusundaki **#{case}** numaralı ceza için itirazın **reddedildi**.', ['guild', 'case']],
  ['appeal.modal.title', 'İtiraz penceresi başlığı', 'Ceza #{case} İtirazı', ['case'], 'label45'],
  ['appeal.modal.label', 'İtiraz pencere alan etiketi', 'Neden haksız olduğunu düşünüyorsun?', [], 'label45'],
]);

section('Otomatik moderasyon (AutoMod)', [
  ['automod.block_message', 'Engellenen kullanıcıya gösterilen mesaj (yeni kurulan kurallar için)', 'Mesajın sunucu kurallarına aykırı olduğu için otomatik olarak engellendi.', [], 'short'],
  ['automod.reason', 'Otomatik uyarı sebebi', 'AutoMod: {rule}{keyword}', ['rule', 'keyword'], 'short'],
  ['automod.dm_extra', 'Otomatik uyarı DM metni', 'Mesajın otomatik moderasyon tarafından engellendi.'],
  ['automod.noperm', 'Bot yetkisi eksik', 'AutoMod kurallarını yönetmek için bana **Sunucuyu Yönet** yetkisi vermelisin.'],
  ['automod.setup.title', 'Kurulum başlığı', '🤖 AutoMod Kurulumu', [], 'title'],
  ['automod.setup.created', 'Kurulum: oluşturuldu', '✅ {name}', ['name'], 'short'],
  ['automod.setup.skipped', 'Kurulum: zaten var', '⏭️ {name} (zaten var)', ['name'], 'short'],
  ['automod.setup.error', 'Kurulum: hata', '❌ {name}: {error}', ['name', 'error']],
  ['automod.setup.nolog', 'Kurulum: mod-log notu', 'ℹ️ `/ayar mod-log` ayarlanmadığı için uyarı bildirimi gönderilmeyecek; ayarladıktan sonra `/otomod kapat` + `/otomod kur` yap.'],
  ['automod.status.title', 'Durum başlığı', '🛡️ Moderasyon Durumu', [], 'title'],
  ['automod.status.f_rules', 'Durum alan: kurallar', 'AutoMod kuralları', [], 'title'],
  ['automod.status.norules', 'Durum: kural yok', 'Hiç kural yok. `/otomod kur` ile oluştur.'],
  ['automod.status.f_verification', 'Durum alan: doğrulama', 'Doğrulama seviyesi', [], 'title'],
  ['automod.status.f_filter', 'Durum alan: içerik taraması', 'Müstehcen içerik taraması', [], 'title'],
  ['automod.status.f_threshold', 'Durum alan: eşik', 'Uyarı eşiği', [], 'title'],
  ['automod.status.threshold', 'Eşik değeri', '{count} uyarı → {minutes} dk susturma', ['count', 'minutes'], 'short'],
  ['automod.status.threshold_off', 'Eşik kapalı', 'kapalı', [], 'short'],
  ['automod.status.footer', 'Durum alt yazı', 'AutoMod ihlalleri otomatik uyarı olarak kaydedilir.', [], 'short'],
  ['automod.verif.0', 'Doğrulama: Yok', 'Yok', [], 'short'],
  ['automod.verif.1', 'Doğrulama: Düşük', 'Düşük (doğrulanmış e-posta)', [], 'short'],
  ['automod.verif.2', 'Doğrulama: Orta', 'Orta (5 dk+ hesap)', [], 'short'],
  ['automod.verif.3', 'Doğrulama: Yüksek', 'Yüksek (10 dk+ üye)', [], 'short'],
  ['automod.verif.4', 'Doğrulama: Çok yüksek', 'Çok yüksek (doğrulanmış telefon)', [], 'short'],
  ['automod.filter.0', 'İçerik taraması: Kapalı', 'Kapalı', [], 'short'],
  ['automod.filter.1', 'İçerik taraması: Rolsüzler', 'Rolü olmayan üyeler', [], 'short'],
  ['automod.filter.2', 'İçerik taraması: Herkes', 'Tüm üyeler', [], 'short'],
  ['automod.disabled', '/otomod kapat: başarılı', '{count} kural silindi.', ['count']],
  ['automod.words.list', 'Kelime listesi', '**Yasaklı kelimeler ({count}):**\n||{words}||', ['count', 'words']],
  ['automod.words.empty', 'Kelime listesi boş', 'Yasaklı kelime listesi boş.'],
  ['automod.words.toolong', 'Kelime çok uzun', 'Kelimeler en fazla 60 karakter olabilir.'],
  ['automod.words.created', 'Kural oluşturuldu', '{count} kelime eklendi ve kural oluşturuldu.', ['count']],
  ['automod.words.createfail', 'Kural oluşturulamadı', 'Kural oluşturulamadı: {error}', ['error']],
  ['automod.words.max', 'Kelime sınırı', 'Discord en fazla 1000 kelimeye izin verir.'],
  ['automod.words.updated', 'Liste güncellendi (ekleme)', 'Kelime listesi güncellendi (toplam {count}).', ['count']],
  ['automod.words.norule', 'Kural yok', 'Yasaklı kelime kuralı yok.'],
  ['automod.words.cleared', 'Tüm kelimeler silindi', 'Tüm kelimeler silindi, kural kaldırıldı.'],
  ['automod.words.left', 'Liste güncellendi (silme)', 'Kelime listesi güncellendi (kalan {count}).', ['count']],
]);

section('Ayar komutu (/ayar)', [
  ['settings.channel_perm', 'Kanalda yetki yok', '{channel} kanalında mesaj/embed gönderme iznim yok.', ['channel']],
  ['settings.channel_set', 'Kanal ayarlandı', '{label} kanalı {channel} olarak ayarlandı.', ['label', 'channel']],
  ['settings.label.modlog', 'Kanal adı: mod-log', 'Mod-log', [], 'short'],
  ['settings.label.report', 'Kanal adı: rapor', 'Rapor', [], 'short'],
  ['settings.label.appeal', 'Kanal adı: itiraz', 'İtiraz', [], 'short'],
  ['settings.level_channel_set', 'Seviye kanalı ayarlandı', 'Seviye duyuruları {channel} kanalına gidecek.', ['channel']],
  ['settings.level_channel_unset', 'Seviye kanalı sıfırlandı', 'Seviye duyuruları mesajın yazıldığı kanalda yapılacak.'],
  ['settings.staff_set', 'Yetkili rolü ayarlandı', 'Yetkili rolü {role} olarak ayarlandı.', ['role']],
  ['settings.staff_unset', 'Yetkili rolü kaldırıldı', 'Yetkili rolü kaldırıldı.'],
  ['settings.threshold_on', 'Ceza eşiği ayarlandı', '**{count}** aktif uyarıda **{minutes} dk** otomatik susturma uygulanacak.', ['count', 'minutes']],
  ['settings.threshold_off', 'Ceza eşiği kapatıldı', 'Otomatik uyarı cezası kapatıldı.'],
  ['settings.show.title', 'Ayar özeti başlığı', '⚙️ Retronex Ayarları', [], 'title'],
  ['settings.show.f_modlog', 'Özet alan: mod-log', 'Mod-log', [], 'title'],
  ['settings.show.f_report', 'Özet alan: rapor', 'Rapor', [], 'title'],
  ['settings.show.f_appeal', 'Özet alan: itiraz', 'İtiraz', [], 'title'],
  ['settings.show.f_level', 'Özet alan: seviye duyuru', 'Seviye duyuru', [], 'title'],
  ['settings.show.f_staff', 'Özet alan: yetkili rolü', 'Yetkili rolü', [], 'title'],
  ['settings.show.f_levelsys', 'Özet alan: seviye sistemi', 'Seviye sistemi', [], 'title'],
  ['settings.show.f_threshold', 'Özet alan: ceza eşiği', 'Ceza eşiği', [], 'title'],
  ['settings.show.f_voice', 'Özet alan: ses hub', 'Özel ses hub', [], 'title'],
  ['settings.show.f_ticketcat', 'Özet alan: bilet kategorisi', 'Bilet kategorisi', [], 'title'],
  ['settings.unset', 'Ayarlanmamış', 'ayarlanmamış', [], 'short'],
  ['settings.msgchannel', 'Mesajın yazıldığı kanal', 'mesaj kanalı', [], 'short'],
  ['settings.none', 'Yok', 'yok', [], 'short'],
  ['settings.on', 'Açık', 'açık', [], 'short'],
  ['settings.off', 'Kapalı', 'kapalı', [], 'short'],
]);

section('Özel ses kanalları', [
  ['voice.name', 'Oluşturulan kanalın adı', '[💎] {username}', ['username'], 'short'],
  ['voice.err.nochannel', 'Hata: kanalda değil', 'Önce bir özel ses kanalına girmelisin.'],
  ['voice.err.notprivate', 'Hata: özel kanal değil', 'Bulunduğun kanal bir özel ses kanalı değil.'],
  ['voice.err.notowner', 'Hata: sahibi değil', 'Bu kanalın sahibi <@{owner}>; sadece o yönetebilir.', ['owner']],
  ['voice.failed', 'İşlem başarısız', 'İşlem başarısız: {error}', ['error']],
  ['voice.locked', 'Kilitlendi', 'Kanal kilitlendi; yeni kimse giremez. (`/ses izin` ile birini davet edebilirsin)'],
  ['voice.unlocked', 'Kilit açıldı', 'Kanal kilidi açıldı.'],
  ['voice.hidden', 'Gizlendi', 'Kanal gizlendi.'],
  ['voice.shown', 'Gösterildi', 'Kanal artık herkese görünür.'],
  ['voice.badname', 'Geçersiz isim', 'Geçersiz isim.'],
  ['voice.renamed', 'İsim değişti', 'Kanal adı **{name}** oldu.', ['name']],
  ['voice.badlimit', 'Geçersiz limit', 'Limit 0 (sınırsız) ile 99 arasında olmalı.'],
  ['voice.limit_set', 'Limit ayarlandı', 'Kullanıcı limiti **{limit}** yapıldı.', ['limit']],
  ['voice.limit_off', 'Limit kaldırıldı', 'Kullanıcı limiti kaldırıldı.'],
  ['voice.allowed', 'İzin verildi', '{user} artık kanala girebilir.', ['user']],
  ['voice.ban_self', 'Kendini yasaklama', 'Kendini yasaklayamazsın.'],
  ['voice.ban_bot', 'Bot yasaklama', 'Botlar için kullanılamaz.'],
  ['voice.banned', 'Yasaklandı', '{user} bu kanaldan yasaklandı.', ['user']],
  ['voice.kick_self', 'Kendini atma', 'Kendini atamazsın.'],
  ['voice.kick_notin', 'Kullanıcı kanalda değil', 'Bu kullanıcı kanalında değil.'],
  ['voice.kicked', 'Atıldı', '{user} kanaldan atıldı.', ['user']],
  ['voice.transfer_invalid', 'Devir: geçersiz', 'Geçerli bir kullanıcı seç.'],
  ['voice.transfer_notin', 'Devir: kanalda değil', 'Kullanıcı kanalda olmalı.'],
  ['voice.transferred', 'Devredildi', 'Kanal sahipliği {user} kullanıcısına devredildi.', ['user']],
  ['voice.claim_self', 'Devral: zaten sahip', 'Zaten kanalın sahibisin.'],
  ['voice.claim_owner_present', 'Devral: sahip kanalda', 'Sahibi hâlâ kanalda; sahiplik devralınamaz.'],
  ['voice.claimed', 'Devralındı', 'Kanalın yeni sahibi sensin.'],
  ['voice.deleted', 'Kanal silindi', 'Kanal silindi.'],
  ['voice.info.f_owner', 'Bilgi alan: Sahip', 'Sahip', [], 'title'],
  ['voice.info.f_limit', 'Bilgi alan: Limit', 'Limit', [], 'title'],
  ['voice.info.f_members', 'Bilgi alan: Üye', 'Üye', [], 'title'],
  ['voice.info.f_lock', 'Bilgi alan: Kilit', 'Kilit', [], 'title'],
  ['voice.info.f_visibility', 'Bilgi alan: Görünürlük', 'Görünürlük', [], 'title'],
  ['voice.info.unlimited', 'Bilgi: sınırsız', 'sınırsız', [], 'short'],
  ['voice.info.locked', 'Bilgi: kilitli', '🔒 kilitli', [], 'short'],
  ['voice.info.open', 'Bilgi: açık', '🔓 açık', [], 'short'],
  ['voice.info.hidden', 'Bilgi: gizli', '🙈 gizli', [], 'short'],
  ['voice.info.visible', 'Bilgi: görünür', '👁️ görünür', [], 'short'],
  ['voice.panel_perm', '/ses panel: yetki', 'Bunun için **Kanalları Yönet** yetkisi gerekir.'],
  ['voice.panel.title', 'Panel başlığı', '🎙️ Özel Ses Kanalı Paneli', [], 'title'],
  ['voice.panel.desc', 'Panel açıklaması', 'Hub kanalına (➕) girince sana özel bir ses kanalı açılır. Aşağıdaki butonlarla **bulunduğun** kanalı yönetebilirsin.\nKullanıcı bazlı işlemler için `/ses izin`, `/ses yasakla`, `/ses at`, `/ses devret` komutlarını kullan.'],
  ['voice.btn.lock', 'Buton: Kilitle', '🔒 Kilitle', [], 'button'],
  ['voice.btn.unlock', 'Buton: Kilidi Aç', '🔓 Kilidi Aç', [], 'button'],
  ['voice.btn.hide', 'Buton: Gizle', '🙈 Gizle', [], 'button'],
  ['voice.btn.show', 'Buton: Göster', '👁️ Göster', [], 'button'],
  ['voice.btn.name', 'Buton: İsim', '✏️ İsim', [], 'button'],
  ['voice.btn.limit', 'Buton: Limit', '👥 Limit', [], 'button'],
  ['voice.btn.claim', 'Buton: Devral', '👑 Devral', [], 'button'],
  ['voice.btn.info', 'Buton: Bilgi', 'ℹ️ Bilgi', [], 'button'],
  ['voice.btn.delete', 'Buton: Sil', '🗑️ Sil', [], 'button'],
  ['voice.modal.name_title', 'İsim penceresi başlığı', 'Kanal Adı', [], 'label45'],
  ['voice.modal.name_label', 'İsim penceresi etiketi', 'Yeni ad', [], 'label45'],
  ['voice.modal.name_ph', 'İsim penceresi ipucu', 'Örn: Habbo Sohbet', [], 'short'],
  ['voice.modal.limit_title', 'Limit penceresi başlığı', 'Kullanıcı Limiti', [], 'label45'],
  ['voice.modal.limit_label', 'Limit penceresi etiketi', 'Limit (0 = sınırsız)', [], 'label45'],
  ['voice.modal.limit_ph', 'Limit penceresi ipucu', '0-99', [], 'short'],
]);

section('Destek merkezi (Bilet)', [
  ['ticket.panel.title', 'Panel başlığı', '🎫 RetroNEX Destek Merkezi', [], 'title'],
  ['ticket.panel.desc', 'Panel açıklaması', 'Aşağıdaki menüden ilgili konuyu seçerek biletini oluşturabilirsin. Talebini ve detayları açılan özel kanalda paylaşırsan sana çok daha hızlı yardımcı olabiliriz.'],
  ['ticket.panel.placeholder', 'Menü yer tutucu metni', 'Bir kategori seçin...', [], 'short'],
  ['ticket.cat.genel.label', 'Kategori 1: ad', '📩 Genel Destek & Öneri', [], 'short'],
  ['ticket.cat.genel.desc', 'Kategori 1: açıklama', 'Topluluk, roller veya genel sorular ve önerileriniz için', [], 'short'],
  ['ticket.cat.sikayet.label', 'Kategori 2: ad', '⚠️ Şikayet & Kural İhlali', [], 'short'],
  ['ticket.cat.sikayet.desc', 'Kategori 2: açıklama', 'Kural ihlalleri, kullanıcı şikayetleri veya dolandırıcılık (scam) bildirimleri', [], 'short'],
  ['ticket.cat.isbirligi.label', 'Kategori 3: ad', '📢 İş Birliği & Tanıtım', [], 'short'],
  ['ticket.cat.isbirligi.desc', 'Kategori 3: açıklama', 'Otel tanıtımları, sunucu ortaklıkları ve reklam talepleri', [], 'short'],
  ['ticket.welcome.title', 'Bilet kanalı karşılama başlığı', '{category}', ['category'], 'title'],
  ['ticket.welcome.desc', 'Bilet kanalı karşılama metni', 'Hoş geldin! Lütfen talebini ve tüm detayları buraya yaz; yetkililer en kısa sürede dönüş yapacak.\nİşin bittiğinde aşağıdaki butonla bileti kapatabilirsin.'],
  ['ticket.topic', 'Bilet kanalı konusu', '{category} | Bilet sahibi: {tag} ({id})', ['category', 'tag', 'id'], 'short'],
  ['ticket.btn.close', 'Buton: Bileti kapat', '🔒 Bileti Kapat', [], 'button'],
  ['ticket.invalid', 'Geçersiz kategori', 'Geçersiz kategori.'],
  ['ticket.exists', 'Zaten açık bilet', 'Zaten açık bir biletin var: <#{channel}>', ['channel']],
  ['ticket.nocategory', 'Kategori bulunamadı', 'Bilet kategorisi bulunamadı, lütfen bir yetkiliye haber ver.'],
  ['ticket.failed', 'Bilet oluşturulamadı', 'Bilet oluşturulamadı: {error}', ['error']],
  ['ticket.created', 'Bilet oluşturuldu', 'Biletin oluşturuldu: {channel}', ['channel']],
  ['ticket.notticket', 'Kayıtlı bilet değil', 'Bu kanal kayıtlı bir bilet değil.'],
  ['ticket.noperm', 'Kapatma yetkisi yok', 'Bu bileti sadece sahibi ya da yetkililer kapatabilir.'],
  ['ticket.closed', 'Bilet kapatıldı', '🔒 Bilet {user} tarafından kapatıldı. Kanal 5 saniye içinde silinecek.', ['user']],
]);

module.exports = entries;
